### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by theKidOfArcrania** [yourPISD/yourpisd#19]
Which license should we use? GNU or MIT or something else?

**Comment by sid-kap** [comment]
[The WTFPL license?](https://en.wikipedia.org/wiki/WTFPL)

**Comment by sid-kap** [comment]
[ChooseALicense.com](http://choosealicense.com/) (made by Github) might be useful. I'm leaning toward MIT.

**Comment by hanli1** [comment]
MIT is decent.
