### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by sid-kap** [yourPISD/yourpisd#2]
@theKidOfArcrania @creativitRy @hanli1 

Just noticed that @theKidOfArcrania and @creativitRy forked of the repo. Looks like the app finally stopped working---I would have expected it to stop working long ago... Anyways, it's great to see you guys trying to maintain it!

Anyway, I (and probably @hanli1 as well) would be happy to answer any questions you might have! Also, if you are interested, we could probably give you guys push access to this repo, or push access to the Google Play developer account. We could also move the repo to a Github group (I think that's the typical procedure for a Github project when the original author no longer wants to maintain ownership).

**Comment by pyrito** [comment]
I was kind of curious about the parser that you guys used. Any details on how it works?

**Comment by pyrito** [comment]
The reason why the app finally broke was due to the change of the gradebook system.

**Comment by sid-kap** [comment]
The parser logic is in https://github.com/sid-kap/yourpisd/blob/master/app/src/main/java/app/sunstreak/yourpisd/net/Parser.java. What kind of details would you like to know?

**Comment by pyrito** [comment]
I was just wondering about the general logic of it. I assume the parser reads through the gradebook and pics out the information it wants? How exactly does it do that? I'm not too experienced in Java since web development has been my thing. This is probably the part that needs fixing because the gradebook system has been completely changed.

**Comment by theKidOfArcrania** [comment]
Actually, there is a two other compatibility issues besides rewriting the parsing logic in the Parser class.

A) Right now, PISD is operating on 9-weeks periods instead of 6-weeks. I and @creativitRy both noticed that the authors have hardcoded these 6-weeks into the program. It might be good if you @sid-kap could help point out where you hardcoded that (even though I already briefly combed for any of this). 

B) One of the sites that this app relies on is the InternetViewerService, which, I could, with little doubt, say that it probably is a service for pinnacle gradebook that creates a JSON string that summarizes the person's grade information? At this moment it does not exist anymore, and apparently it is because PISD switched to a new provider called "Wazzle Solutions". The App heavily relies on information on this JSON, so we may need to restructure large parts of the code.

Currently I am looking into this and seeing how I can fix this app for later devs.

**Comment by sid-kap** [comment]
@pyrito I'll give you a brief description of how the app gets to the gradebook page, and how it reads grades from there. Keep in mind that, since PISD apparently no longer uses Pinnacle (according to @theKidOfArcrania), many of these details may have changed now. 

**How it gets to the gradebook page:** There is some code that first logs in to myPISD (either the student or parent page). Then it clicks on the "Go to Gradebook" link, which is actually a link to "Passthrough" aspx page. The Passthrough page contains a hidden <form> and <input> tags which contains the username and password for the actual  gradebook (Pinnacle). (This password change every few hours.) When you access the Passthrough page on the web, it has some Javascript (I think) which automatically submits the form, which sends you to the Pinnacle gradebook. To simulate this programmatically, you have to read the <input> tags and then send a post request to Pinnacle with the username and password.

**How it reads the grades:** Once you're logged into Pinnacle, you have a Pinnacle cookie, so you can request any page inside Pinnacle. The app loads all the grades, for every class, on login. (This is why login is so slow.) It first sends an HTTP request for the grade summary, and then from there sends an HTTP request for each six-weeks detail for each class. It parses the HTML that is returned using the Jsoup HTML parsing library. I'd suggest reading about HTML and Jsoup for more information.

**Comment by theKidOfArcrania** [comment]
To correct you @sid-kap, PISD still uses pinnacle gradebook, but PISD has revamped the GUI of the gradebook. Also the process has been simplified significantly (instead of using the Passthrough.aspx page, PISD now directs you the the login page of pinnacle gradebook and wants you to login using school credentials).

**Comment by sid-kap** [comment]
Oh, I see. Thanks for the clarification. That's really nice! Dealing with the Passthrough credentials made the login logic more complicated, and slower.

**Comment by sid-kap** [comment]
@theKidOfArcrania 

A) Wow, that's a surprise! Do you have any idea why they switched to 9-weeks periods? I wonder how that changes the GPA metagame :P. Sure, I'll try to find places that assume 6-weeks periods, and I'll let you know.

B) Yes, that JSON we received from InternetViewerService was really useful. We found it by using Chrome Dev Tools and looking at all the things that get loaded when you log into Pinnacle. Maybe it's still there, but by a different name? If not, you could maybe get the same information by parsing the HTML on the Grade Summary page.

**Comment by sid-kap** [comment]
Here are some places that are hard-coded with 6-weeks periods:

[Change "Current Six Weeks" to "Current Nine Weeks"](https://github.com/sid-kap/yourpisd/blob/master/app/src/main/java/app/sunstreak/yourpisd/MainActivity.java#L125)
[Change the `4`s to `3`s, since now each semester only has two nine-week periods and an exam](https://github.com/sid-kap/yourpisd/blob/master/app/src/main/java/app/sunstreak/yourpisd/MainActivity.java#L549)

**Comment by sid-kap** [comment]
By the way, I highly suggest getting rid of this [jank](https://github.com/sid-kap/yourpisd/blob/master/app/src/main/java/app/sunstreak/yourpisd/util/HTTPResponse.java) [HTTP client](https://github.com/sid-kap/yourpisd/blob/master/app/src/main/java/app/sunstreak/yourpisd/util/Request.java) that we made. We wanted to use [Unirest](http://unirest.io/java.html) but we couldn't figure out how to install the JAR :/

**Comment by theKidOfArcrania** [comment]
Okay @sid-kap should the app just load the pages for specific assignments when the user clicks on the tab for that period? (The app will still cache and maybe auto refresh every hour or so, but that might expedite the login process?)

**Comment by sid-kap** [comment]
Yeah, that sounds like a big improvement to me.

**Comment by sid-kap** [comment]
I'm going to make some issues for potential things to fix, if y'all are interested

**Comment by pyrito** [comment]
Yeah go ahead, I'm in.

**Comment by theKidOfArcrania** [comment]
Could you @sid-kap explain what the difference is betweeen the two activities `ClassSwipeActivity` and `MainActivity`?

**Comment by sid-kap** [comment]
`MainActivity` is the first thing you see after you log in: it shows your picture, name, ID, and grade summary.

`ClassSwipeActivity` is the grade detail view, where you can see the grades for individual assignments for each grading period.

**Comment by sid-kap** [comment]
TBH, `ClassSwipeActivity` isn't a great name. We called it that because you can swipe left and right to switch between classes. Maybe `GradeDetailActivity` or something would probably be better.

**Comment by hanli1** [comment]
There are some very janky things going on in the source like @sid-kap said. Speaking personally, when we started with this project it was more of a "move fast break things", which isn't that good for long term dev and maintenance. Again, we had expected this to break a long time ago, but I'm glad someone's decided to take up on this project. Feel free to ask me any questions as well but I mainly did the front end of the app.

**Comment by pyrito** [comment]
Haha I understand why documentation is so crucial in app development now. Either way, I have been able to work around.

**Comment by theKidOfArcrania** [comment]
uhmm... yeah, I'm probably going to leave the front-end mostly intact, but I will need to (almost) completely restructure the back-end part.
