### ISSUE TITLE
Pressing any grade in the semester tab opens 1st class

### ISSUE THREAD

**Issue by creativitRy** [yourPISD/yourpisd#24]
Should open the class with the grade

**Comment by sid-kap** [comment]
This information is passed as extras in the intent that MainActivity builds to open ClassSwipeActivity. The relevant code is in the `onCreate` method in `ClassSwipeActivity`.

**Comment by theKidOfArcrania** [comment]
The reason why that is broken is because I changed a few of the intent extra names, and also changed the meaning of the values. So I am working on it.
