### ISSUE TITLE
What happens when grade is X?

### ISSUE THREAD

**Issue by creativitRy** [yourPISD/yourpisd#28]
When grade is a string that cannot be parsed to a double.

**Comment by sid-kap** [comment]
Good catch! I don't think our code handles this case. (Also, somehow, I don't remember ever running into this problem. Weird.)

**Comment by sid-kap** [comment]
The current fix just sets it to -1, which we interpret as the grade being missing. Ideally, we should actually show an X, right?

I'm thinking we could set it to -2 or something to indicate it's an X, and then when displaying the grade show an X if the grade is -2?

**Comment by theKidOfArcrania** [comment]
Yes I will intend on changing it to -2. I will need to first gather up some test cases of how the "X" will be displayed. I am just not sure how the "X" will be displayed at all.
