### ISSUE TITLE
Confirmation buttons do not appear when a new prompt window is opened

### ISSUE THREAD

**Issue by tiggermcwigger** [yourPISD/yourpisd#31]
The "okay" buttons do not appear. They seem to function. Pictures are attached. The device is LG G3 running Andriod 6.0.

![14689163_1060100950773781_2006611257_o](https://cloud.githubusercontent.com/assets/22806993/19336471/3968af1e-90d1-11e6-8f2b-f736a209f7f8.png)
![14632540_1060100397440503_1694093142_o](https://cloud.githubusercontent.com/assets/22806993/19336473/3ba32d9a-90d1-11e6-8f5a-e464ca82b005.png)

**Comment by theKidOfArcrania** [comment]
Yeah sorry that's an android issue.... On the newer android phones, the okay button only appears after you touch the bottom of the screen.

**Comment by sid-kap** [comment]
Wow, that's really strange. Is this an Android bug?

**Comment by theKidOfArcrania** [comment]
It doesn't seem like a bug, and I had to deal with that issue during testing, yeah but I found what could be used to solve it [here](http://stackoverflow.com/questions/33228454/android-6-0-dialog-text-doesnt-appear)

**Comment by theKidOfArcrania** [comment]
Should be fixed in next version.
