### ISSUE TITLE
Tabs or spaces?

### ISSUE THREAD

**Issue by sid-kap** [yourPISD/yourpisd#8]
All of the old code is indented with tabs, but I noticed that some of the new code that you guys added is indented using spaces.

Should we settle on one or the other? I believe spaces is usually preferred. (I didn't know this three years ago when we started the project.) If spaces, how many spaces?

**Comment by theKidOfArcrania** [comment]
Oh whoops, I think intellij likes using spaces. But I think if we settle with spaces, 4 spaces seem fine?

**Comment by sid-kap** [comment]
4 spaces sounds good to me! Any objections?
